### PR TITLE
fixes for 0.7

### PR DESCRIPTION
**Pull request by kleinschmidt**
WIP. Starting with running femtocleaner.

### CODE REVIEW

**Comment by dmbates** [comment]
I was able to rebase this branch on master painlessly (a first for me!) and it now passes tests on v0.7.0-beta.  The only remaining warning is
```
┌ Warning: `reduce(op, v0, itr)` is deprecated, use `reduce(op, itr; init=v0)` instead
│   caller = coefnames(::ModelFrame) at modelframe.jl:260
└ @ StatsModels modelframe.jl:260
```
and I think that can be changed if the `REQUIRE` file lists `julia 0.7.0-beta`.  Shall I go ahead and make those changes?

**Comment by kleinschmidt** [comment]
Sounds good, thanks @dmbates, and congratulations on a painless rebase :) I'll let you push your rebased changes here.

**Comment by dmbates** [comment]
Travis failures are because `.travis.yml` proposes to test on version 0.7 which doesn't exist yet.

**Comment by kleinschmidt** [comment]
I thought 0.7 would use the latest release on that series?

(please pardon my thumb-typing)

--
dave.f.kleinschmidt@gmail.com
http://davekleinschmidt.com
413-884-2741

**Comment by dmbates** [comment]
I can't see what is causing the difference but Travis succeeds on `nightly` and fails on `0.7`.

**Comment by dmbates** [comment]
From the discussion on slack it looks as if the failures are harmless so I will merge this.

**Pull request merged**
