### PR TITLE
Add a formula(model) accessor

### PR DESCRIPTION
**Pull request by kleinschmidt**
There's currently no way to access the formula for a fitted model without
digging around in the innards of `Table(Regression|Statistical)Model`.  This
remedies that.

### CODE REVIEW

**Review by ararslan — APPROVED** [review]

**Comment by ararslan** [comment]
CI failure on Julia 1.0 is unrelated: DataFrames version issue.

**Comment by kleinschmidt** [comment]
CI failure relatedness be damned, we're doing this right

**Comment by ararslan** [comment]
Now versioning issues with Missings and CategoricalArrays

**Review by ararslan — APPROVED** [review]

**Comment by ararslan** [comment]
Tests for the added lines would be nice, but also ¯\\\_(ツ)\_/¯

**Review by ararslan — APPROVED** [review]
Third time's the charm

**Pull request merged**
