### PR TITLE
Changes for v0.11 of DataFrames

### PR DESCRIPTION
**Pull request by dmbates**
Also some code cleanup.  `Compat.view` can now be `view`.  In the tests `Base.Test` -> `Compat.Test`

### CODE REVIEW

**Comment by Nosferican** [comment]
I believe all those were fixed in #33.

**Comment by dmbates** [comment]
@Nosferican Okay.  Thanks for letting me know.  I'll watch for #33 to be merged.

**Comment by kleinschmidt** [comment]
I'm closing this since everything except the docs changes are merged with #33 and #46.  Open a new PR with the docs if you want, @dmbates ?

**Comment by dmbates** [comment]
Yes, thanks.  I should have mentioned in #46 that I this PR should be closed.

**Pull request closed without merging**
