### PR TITLE
RIP REQUIRE, hello Project.toml

### PR DESCRIPTION
**Pull request by kleinschmidt**
In preparation for tagging a release, this replaces REQUIRE and test/REQUIRE with Project.toml

### CODE REVIEW

**Comment by ararslan** [comment]
Needs a version underneath uuid in order to be tagged, otherwise LGTM if CI agrees

**Comment by kleinschmidt** [comment]
And just to be clear, merging a Project.toml with a version is **not** enough to trigger the registration bot right?  THat requires a manual step?

**Comment by ararslan** [comment]
Correct. You do at-JuliaRegistrator `register()` and it uses the version in Project.toml to make a PR against the General registry, then once that's merged, TagBot makes a tag for the version on the repo.

**Comment by ararslan** [comment]
Still needs a version...

**Comment by kleinschmidt** [comment]
well I'm a moron. time to make another PR like an idiot

**Pull request merged**
