### PR TITLE
Specialize apply_schema to Schema for lead/lag

### LINKED ISSUE #146: Method ambiguity for lead/lag terms
I'm getting a method error on schema application when using a lead/lag term. I didn't think this was a GLM thing, but I'm happy to move this over there if it is a GLM thing.

EDIT: I slimmed the MWE down even more.

MWE:

```julia
using DataFrames, StatsModels, GLM

df = DataFrame(a = randn(10), b=randn(10))
f = @formula(a ~ 1 + lag(b, 1))
fitted = lm(f, df)
```

Error:

```julia
ERROR: MethodError: StatsModels.apply_schema(::FunctionTerm{typeof(lag),getfield(Main, Symbol("##383#384")),(:b,)}, ::StatsModels.FullRank, ::Type{LinearModel}) is ambiguous. Candidates:
  apply_schema(t::AbstractTerm, schema::StatsModels.FullRank, Mod::Type) in StatsModels at /home/cameron/.julia/packages/StatsModels/G9zlM/src/schema.jl:313
  apply_schema(t::FunctionTerm{F,Fanon,Names} where Names where Fanon, sch, ctx::Type) where F<:Union{typeof(lag), typeof(lead)} in StatsModels at /home/cameron/.julia/packages/StatsModels/G9zlM/src/temporal_terms.jl:30
Possible fix, define
  apply_schema(::FunctionTerm{F<:Union{typeof(lag), typeof(lead)},Fanon,Names} where Names where Fanon, ::StatsModels.FullRank, ::Type)
Stacktrace:
 [1] _broadcast_getindex_evalf(::typeof(apply_schema), ::FunctionTerm{typeof(lag),getfield(Main, Symbol("##383#384")),(:b,)}, ::StatsModels.FullRank, ::Type) at ./broadcast.jl:578
 [2] _broadcast_getindex at ./broadcast.jl:551 [inlined]
 [3] (::getfield(Base.Broadcast, Symbol("##19#20")){Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple},Nothing,typeof(apply_schema),Tuple{Tuple{ConstantTerm{Int64},FunctionTerm{typeof(lag),getfield(Main, Symbol("##383#384")),(:b,)}},Base.RefValue{StatsModels.FullRank},Base.RefValue{Type{LinearModel}}}}})(::Int64) at ./broadcast.jl:953
 [4] ntuple at ./tuple.jl:160 [inlined]
```

### PR DESCRIPTION
**Pull request by kleinschmidt**
By analogy with how other built-in terms are handled since the Schema type was
introduced.

Fixes #146

### CODE REVIEW

**Comment by kleinschmidt** [comment]
I'm not familiar with that, what does it do that detecting the ambiguity errors themselves doesn't?

**Comment by oxinabox** [comment]
You write

```
@test isempty(detect_ambiguities(Base, Core, StatsModels))
```

inside your `test/runtest.jl` and it goes through and checks that no ambiguities exist.

**Comment by kleinschmidt** [comment]
Looks like that catches ambiguities that are internal to Base or Core too though...

**Comment by oxinabox** [comment]
> Looks like that catches ambiguities that are internal to Base or Core too though...

Yes, but Base and Core don't have any. So ...

**Comment by oxinabox** [comment]
alteratively, can just do

```
@test isempty(detect_ambiguities(StatsModels))
```

**Comment by kleinschmidt** [comment]
The issue is that there aren't any ambiguities in the code as far as it exists now...but they have a nasty habit of turning up with extensions (like these temporal terms)

**Comment by oxinabox** [comment]
Seems like a good reason to add that test then?

**Comment by kleinschmidt** [comment]
.........indeed

**Comment by kleinschmidt** [comment]
BTW, when I run `Test.detect_ambiguities(Core, Base)` I get: 

```
68-element Array{Tuple{Method,Method},1}:
 ((::Type{StaticArrays.SArray{Tuple{S1,S2},T,2,L} where T})(x::Tuple{Vararg{Any,L}}) where {S1, S2, L} in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/SMatrix.jl:41, (::Type{SA})(x::Tuple{Tuple{Tuple{#s162} where #s162<:Tuple}}) where SA<:StaticArrays.StaticArray in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/convert.jl:1)                             
 ((::Type{StaticArrays.MArray{Tuple{S1,S2},T,2,L} where L where T where S2})(x::Tuple{Vararg{T,L}} where T) where {S1, L} in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/MMatrix.jl:21, (::Type{SA})(x::Tuple{Tuple{Tuple{#s162} where #s162<:Tuple}}) where SA<:StaticArrays.StaticArray in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/convert.jl:1)          
 (convert(::Type{S}, x::T) where {S, T<:(Union{CategoricalArrays.CategoricalString{R}, CategoricalArrays.CategoricalValue{T,R} where T} where R)} in CategoricalArrays at /home/dave/.julia/packages/CategoricalArrays/JFETm/src/value.jl:91, convert(::Type{T}, x) where T>:Union{Missing, Nothing} in Base at missing.jl:70)                                                                              
 ((::Type{StaticArrays.SArray{S,T,N,L} where L})(x::Tuple) where {S<:Tuple, T, N} in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/SArray.jl:33, (::Type{SA})(x::Tuple{Tuple{Tuple{#s162} where #s162<:Tuple}}) where SA<:StaticArrays.StaticArray in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/convert.jl:1)                                                   
 (checkbounds(::Type{Bool}, ::ShiftedArrays.CircShiftedArray, I...) in ShiftedArrays at /home/dave/.julia/packages/ShiftedArrays/iqIVk/src/circshiftedarray.jl:98, checkbounds(::Type{Bool}, A::AbstractArray, i::Union{AbstractArray{#s627,N} where N where #s627<:CartesianIndex, CartesianIndex}) in Base at multidimensional.jl:472)                                                                    
 ((::Type{StaticArrays.MArray{Tuple{S},T,1,S} where T})(x::Tuple{Vararg{T,S}}) where {S, T} in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/MVector.jl:20, (::Type{SA})(x::Tuple{Tuple{Tuple{#s162} where #s162<:Tuple}}) where SA<:StaticArrays.StaticArray in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/convert.jl:1)                                        
 (convert(::Type{S}, x::T) where {S, T<:(Union{CategoricalArrays.CategoricalString{R}, CategoricalArrays.CategoricalValue{T,R} where T} where R)} in CategoricalArrays at /home/dave/.julia/packages/CategoricalArrays/JFETm/src/value.jl:91, convert(::Type{SubString{S}}, s::AbstractString) where S<:AbstractString in Base at strings/substring.jl:50)                                                  
 ((::Type{StaticArrays.SArray{S,T,N,L}})(x::Tuple{Vararg{T,L}}) where {S, T, N, L} in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/SArray.jl:22, (::Type{SA})(x::Tuple{Tuple{Tuple{#s162} where #s162<:Tuple}}) where SA<:StaticArrays.StaticArray in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/convert.jl:1)                                                  
 ((::Type{StaticArrays.SArray{S,T,N,L} where L where N})(x::Tuple) where {S<:Tuple, T} in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/SArray.jl:40, (::Type{SA})(x::Tuple{Tuple{Tuple{#s162} where #s162<:Tuple}}) where SA<:StaticArrays.StaticArray in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/convert.jl:1)                                              
 (copyto!(dest::RecursiveArrayTools.ArrayPartition, bc::Base.Broadcast.Broadcasted) in RecursiveArrayTools at /home/dave/.julia/packages/RecursiveArrayTools/peaIl/src/array_partition.jl:245, copyto!(dest::AbstractArray, bc::Base.Broadcast.Broadcasted{#s627,Axes,F,Args} where Args<:Tuple where F where Axes where #s627<:Base.Broadcast.AbstractArrayStyle{0}) in Base.Broadcast at broadcast.jl:869)
 ((::Type{StaticArrays.SizedArray{Tuple{S1,S2},T,2,M} where M where T})(x::Tuple{Vararg{T,L}}) where {S1, S2, T, L} in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/SizedArray.jl:73, (::Type{SA})(x::Tuple{Tuple{Tuple{#s162} where #s162<:Tuple}}) where SA<:StaticArrays.StaticArray in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/convert.jl:1)             
 (checkbounds(::Type{Bool}, ::ShiftedArrays.CircShiftedArray, I...) in ShiftedArrays at /home/dave/.julia/packages/ShiftedArrays/iqIVk/src/circshiftedarray.jl:98, checkbounds(::Type{Bool}, A::AbstractArray, I::Base.LogicalIndex{#s627,#s626} where #s626<:AbstractArray{Bool,1} where #s627) in Base at multidimensional.jl:619)                                                                        
 ((::Type{StaticArrays.SHermitianCompact{N,T,L}})(a::Tuple) where {N, T, L} in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/SHermitianCompact.jl:63, (::Type{SA})(x::Tuple{Tuple{Tuple{#s162} where #s162<:Tuple}}) where SA<:StaticArrays.StaticArray in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/convert.jl:1)                                              
 ⋮                                                                                                                                                                                                                                                                                                                                                                                                          
 ((::Type{Scalar{T} where T})(x::Tuple{T}) where T in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/Scalar.jl:9, (::Type{SA})(x::Tuple{Tuple{Tuple{#s162} where #s162<:Tuple}}) where SA<:StaticArrays.StaticArray in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/convert.jl:1)                                                                                   
 ((::Type{StaticArrays.SArray{Tuple{S},T,1,S} where T where S})(x::Tuple{Vararg{Any,S}}) where S in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/SVector.jl:18, (::Type{SA})(x::Tuple{Tuple{Tuple{#s162} where #s162<:Tuple}}) where SA<:StaticArrays.StaticArray in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/convert.jl:1)                                   
 ((::Type{StaticArrays.SHermitianCompact})(a::StaticArrays.StaticArray{Tuple{N,N},T,2}) where {N, T} in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/SHermitianCompact.jl:82, (::Type{SSC})(a::SSC) where SSC<:StaticArrays.SHermitianCompact in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/SHermitianCompact.jl:85)                                            
 ((::Type{StaticArrays.SizedArray{Tuple{S},T,1,M} where M where T})(x::Tuple{Vararg{T,L}}) where {S, T, L} in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/SizedArray.jl:69, (::Type{SA})(x::Tuple{Tuple{Tuple{#s162} where #s162<:Tuple}}) where SA<:StaticArrays.StaticArray in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/convert.jl:1)                      
 ((::Type{FV})(x::Tuple{Vararg{Any,N}}) where {N, FV<:(StaticArrays.FieldVector{N,T} where T)} in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/FieldVector.jl:20, (::Type{SA})(x::Tuple{Tuple{Tuple{#s162} where #s162<:Tuple}}) where SA<:StaticArrays.StaticArray in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/convert.jl:1)                                 
 ((::Type{StaticArrays.SizedArray{S,T,N,M} where M})(x::Tuple) where {S, T, N} in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/SizedArray.jl:47, (::Type{SA})(x::Tuple{Tuple{Tuple{#s162} where #s162<:Tuple}}) where SA<:StaticArrays.StaticArray in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/convert.jl:1)                                                  
 ((::Type{StaticArrays.MArray{S,T,N,L} where L where N where T})(x::T) where {S, T<:Tuple} in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/MArray.jl:54, (::Type{SA})(x::Tuple{Tuple{Tuple{#s162} where #s162<:Tuple}}) where SA<:StaticArrays.StaticArray in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/convert.jl:1)                                          
 ((::Type{StaticArrays.SizedArray{S,T,N,M} where M where N})(x::Tuple) where {S, T} in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/SizedArray.jl:48, (::Type{SA})(x::Tuple{Tuple{Tuple{#s162} where #s162<:Tuple}}) where SA<:StaticArrays.StaticArray in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/convert.jl:1)                                             
 (checkbounds(::Type{Bool}, ::ShiftedArrays.ShiftedArray, I...) in ShiftedArrays at /home/dave/.julia/packages/ShiftedArrays/iqIVk/src/shiftedarray.jl:104, checkbounds(::Type{Bool}, A::AbstractArray, I::Base.LogicalIndex) in Base at multidimensional.jl:621)                                                                                                                                           
 ((::Type{StaticArrays.MArray{S,T,N,L}})(x::Tuple{Vararg{T,L}}) where {S, T, N, L} in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/MArray.jl:24, (::Type{SA})(x::Tuple{Tuple{Tuple{#s162} where #s162<:Tuple}}) where SA<:StaticArrays.StaticArray in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/convert.jl:1)                                                  
 (reduce(op, a::StaticArrays.StaticArray) in StaticArrays at /home/dave/.julia/packages/StaticArrays/3KEjZ/src/mapreduce.jl:164, reduce(::typeof(hcat), A::AbstractArray{#s66,1} where #s66<:(Union{AbstractArray{T,1}, AbstractArray{T,2}} where T)) in Base at abstractarray.jl:1378)                                                                                                                     
 (convert(::Type{S}, x::T) where {S, T<:(Union{CategoricalArrays.CategoricalString{R}, CategoricalArrays.CategoricalValue{T,R} where T} where R)} in CategoricalArrays at /home/dave/.julia/packages/CategoricalArrays/JFETm/src/value.jl:91, convert(::Type{T}, s::AbstractString) where T<:AbstractString in Base at strings/basic.jl:209)                                                                
```

on 1.3-rc2

**Comment by oxinabox** [comment]
Might be worth opening issues on those packages

To catch apply_schema etc errors only need 
```
@test isempty(detect_ambiguities(StatsModels))
```

**Comment by kleinschmidt** [comment]
The other issue I just ran into is: when I run `detect_ambiguities` outside the test suite everything looks good.  But because the test suit introduces additional methods for functions from StatsModels, it fails when run as part of the test suite.  I could move the ambiguity test to the very front but...that seems a bit of a hack.

**Comment by kleinschmidt** [comment]
Okay I marked the failing test as broken and added a "clean" one at the start.

**Pull request merged**
