### PR TITLE
Fix bug with predict(mm::TableRegressionModel, data; kwargs...)

### LINKED ISSUE #125: `predict(model, df)` fails if `df` does not contain dependent variable (ERROR: type NamedTuple has no field)
Cross-posted from https://github.com/JuliaStats/GLM.jl/issues/315

`predict(model, df)` works fine if `df` contains the dependent variable, but fails if `df` does not contain the dependent variable. I think this is a bug, because you should be able to predict with just the independent variables.

### Minimum working example (MWE)

```julia
using GLM, RDatasets
df = RDatasets.dataset("MASS", "Boston")
f = @formula(MedV ~ 1 + Crim + Zn + Indus + Chas + NOx + Rm + Age + Dis + Rad + Tax + PTRatio + Black + LStat)
model = glm(f, df, Normal(), IdentityLink())
predict(model, df) # this works
deletecols!(df, [:MedV])
predict(model, df) # this gives an error
```

Running the last line gives this error:
```
ERROR: type NamedTuple has no field MedV
Stacktrace:
 [1] #134 at ./none:0 [inlined]
 [2] iterate(::Base.Generator{NTuple{14,Symbol},getfield(Base, Symbol("##134#137")){NamedTuple{(:Crim, :Zn, :Indus, :Chas, :NOx, :Rm, :Age, :Dis, :Rad, :Tax, :PTRatio, :Black, :LStat),Tuple{Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Int64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Int64,1},Array{Int64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1}}}}}) at ./generator.jl:47
 [3] append_any(::Any, ::Vararg{Any,N} where N) at ./essentials.jl:674
 [4] (::Type{NamedTuple{names,T} where T<:Tuple})(::NamedTuple) at ./namedtuple.jl:87
 [5] missing_omit(::NamedTuple{(:Crim, :Zn, :Indus, :Chas, :NOx, :Rm, :Age, :Dis, :Rad, :Tax, :PTRatio, :Black, :LStat),Tuple{Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Int64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Int64,1},Array{Int64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1}}}, ::FormulaTerm{ContinuousTerm{Float64},MatrixTerm{Tuple{InterceptTerm{true},ContinuousTerm{Float64},ContinuousTerm{Float64},ContinuousTerm{Float64},ContinuousTerm{Float64},ContinuousTerm{Float64},ContinuousTerm{Float64},ContinuousTerm{Float64},ContinuousTerm{Float64},ContinuousTerm{Float64},ContinuousTerm{Float64},ContinuousTerm{Float64},ContinuousTerm{Float64},ContinuousTerm{Float64}}}}) at /Users/dilum/.julia/packages/StatsModels/ZHkQE/src/modelframe.jl:77
 [6] #predict#74(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}}, ::Function, ::StatsModels.TableRegressionModel{GeneralizedLinearModel{GlmResp{Array{Float64,1},Normal{Float64},IdentityLink},DensePredChol{Float64,LinearAlgebra.Cholesky{Float64,Array{Float64,2}}}},Array{Float64,2}}, ::DataFrame) at /Users/dilum/.julia/packages/StatsModels/ZHkQE/src/statsmodel.jl:162
 [7] predict(::StatsModels.TableRegressionModel{GeneralizedLinearModel{GlmResp{Array{Float64,1},Normal{Float64},IdentityLink},DensePredChol{Float64,LinearAlgebra.Cholesky{Float64,Array{Float64,2}}}},Array{Float64,2}}, ::DataFrame) at /Users/dilum/.julia/packages/StatsModels/ZHkQE/src/statsmodel.jl:158
 [8] top-level scope at none:0
```

This is on Julia v1.1.1, GLM v1.1.1, and StatsModels v0.6.0.

### PR DESCRIPTION
**Pull request by DilumAluthge**
Fixes #125

Patch thanks to @kleinschmidt

### CODE REVIEW

**Comment by kleinschmidt** [comment]
Can you add tests based on your MWE to make sure this is fixed?

**Comment by DilumAluthge** [comment]
Hmmm my MWE was based on GLM, but GLM isn't a test time dependency of StatsModels.

**Comment by DilumAluthge** [comment]
Is there a way that I can make a regression model without GLM?

**Comment by kleinschmidt** [comment]
There are some examples of "dummy models" in the tests that you could check out...

**Comment by DilumAluthge** [comment]
I've added some tests!

**Comment by DilumAluthge** [comment]
Alright I've added tests and all of the Travis jobs pass.

**Comment by kleinschmidt** [comment]
Looks good to me! Thanks for the fix. Can you also bump the patch version?

**Comment by DilumAluthge** [comment]
Done!

**Comment by DilumAluthge** [comment]
Thanks @kleinschmidt! Can you also make a new release?

**Comment by kleinschmidt** [comment]
@JuliaRegistrator register

**Comment by kleinschmidt** [comment]
JuliaRegistries/General#1666

**Comment by DilumAluthge** [comment]
Thanks!

**Pull request merged**
