### PR TITLE
Remove stray comment in the docs

### PR DESCRIPTION
**Pull request by oxinabox**

### CODE REVIEW

**Comment by kleinschmidt** [comment]
IIRC this comment is actually necessary so that the code block and be interpreted as a doctest...

**Comment by kleinschmidt** [comment]
(which in turn is required so that the types/methods defined in it can be used in later doctest blocks)

**Comment by kleinschmidt** [comment]
https://travis-ci.org/JuliaStats/StatsModels.jl/jobs/516250063#L692

**Comment by oxinabox** [comment]
Really?
There must be a better way
It shows up in the content

**Comment by kleinschmidt** [comment]
The only alternative as far as I could tell would be to duplicate the code in that block in a `@meta` block which defeats the purpose of a doctest. Or putting `julia> ` in front of every line in that block which...

**Pull request closed without merging**
